### ISSUE TITLE
XML Forms definition file

### ISSUE THREAD

**Issue by pathintegral** [mjordan/islandora_feeds#12]
Hi,
I'm following the guideline and now I'm on "Generating an XML Forms definition file and XSD Schema for your objects" part. I got an error when I try to reach the file via Structure > [Drupal content type] > Edit > Islandora Feeds. 

The error message as follows:
Fatal error: Call to undefined function dd() in /var/www/drupal7/sites/all/modules/islandora_feeds/islandora_feeds.module on line 211

Thanks.

Edit: Using print_r() instead of dd() solved my problem for now.

**Comment by mjordan** [comment]
@pathintegral my apologies for leaving debugging functions in pushed code. `dd()` is an alias for `drupal_debug()`, which is provided by the [Devel](https://www.drupal.org/project/devel) contrib module. I've removed the calls to `dd()` and pushed up a clean version of the code.

In general, I have abandoned development on the Islandora Feeds module and shifted to a more general-purpose alternative, the [XML Solution Pack](https://github.com/mjordan/islandora_solution_pack_xml), which we have been running in production for well over a year.  The main thing that Islandora Feeds provides that the XML Solution Pack doesn't is the awesome power of Feeds. But if you need Feeds, please feel free to fork and add to this module.

**Comment by pathintegral** [comment]
@mjordan Thanks for kind reply. I'm not familiar with Drupal so that i looked for alternative to dd. Yet, now i can clearly see the problem.

As you stated, Feeds with huge capability is more likely to apply for my use-case. After some development and obtain ready-to-use production level applications, I'll be delighted to fork and improve your repository both with codes and use-cases.

Thanks.
